### PR TITLE
fix: error when {encoding} was set

### PR DESCRIPTION
**Pull request by laggingreflex**
When using {encoding} option this was giving an error: TypeError: Cannot read property 'setEncoding' of null

setEncoding can only be done on a readable it seems

https://nodejs.org/api/stream.html#stream_readable_setencoding_encoding

### CODE REVIEW

**Comment by timdp** [comment]
Shouldn't we check if `stdin` is not null and if it has a `setEncoding` then?

**Comment by laggingreflex** [comment]
Before this I actually updated the `parseStdioOption` method to check the status of `ignoreStdin` as well. 

But then I figured since `stdin` is a writable stream and it seems they don't have a `setEncoding` method anyways, we shouldn't even bother, no?.


But if you suggest just checking whether its null could we simplify even further and get rid of the `parseStdioOption` method altogether? see added commit

**Comment by timdp** [comment]
I think this will break if you pass `'ignore'` for stdout and/or stderr. IIRC it makes `.stdout` and `.stderr` undefined, so the `.on('data', ...)` fails.

**Comment by laggingreflex** [comment]
`.on('data', ...)` would be inside this check:
```
    if (childProcess.stdout) {
      ...
      childProcess.stdout.on('data', (data) => {
        ...
      })
    }
```

**Comment by timdp** [comment]
Whoops, missed that. I refactored some logic into functions and merged, thanks!

**Pull request merged**
