### PR TITLE
feat(typings): added TypeScript typings

### PR DESCRIPTION
**Pull request by stephenlautier**
Created PR as promised @timdp 

Closes https://github.com/zentrick/cross-spawn-promise/issues/56

### CODE REVIEW

**Comment by timdp** [comment]
Thanks! :+1:

**Comment by stephenlautier** [comment]
@timdp Sorry for bothering you again, do you have any plans when to release? since they will be available on next release

thanks

**Comment by timdp** [comment]
You have every right to bother me. :smile:

Version 0.10.1 comes with the typings!

**Comment by stephenlautier** [comment]
@timdp awesome thanks!

**Pull request merged**
