### PR TITLE
fix: support encoding

### PR DESCRIPTION
**Pull request by laggingreflex**
Ermm.. somehow forgot to actually `setEncoding` in my last commit. -_-

### CODE REVIEW

**Comment by timdp** [comment]
Ah, I thought that you were somehow setting it from the outside or that the option was being handled by cross-spawn.

Actually, to avoid confusion, we should probably remove the option before passing options to cross-spawn then.

Also, should it affect stdin? Perhaps this needs to work similar to the `stdio` option, where you can pass either a string for all three streams or an object configuring each of them individually.

**Comment by laggingreflex** [comment]
In the default [`exec`](https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback) methods it doesn't affect `stdin` and can only be a string affecting both "stdout" and "stderr".

Updated to delete it from the options before passing to cross-spawn.

**Comment by laggingreflex** [comment]
Actually in `spawnSync` it does says it affects all streams, including stdin, but it still accepts only a single string.  

Updated to set stdin's encoding as well.

**Comment by timdp** [comment]
Thanks! :+1:

**Pull request merged**
